production:
 access_key_id: AKIAIJUGMKYECWUFG2VQ
 secret_access_key: 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
 bucket: mtm_test_data

test:
 access_key_id: AKIAIJUGMKYECWUFG2VQ
 secret_access_key: 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
 bucket: mtm_test_data

staging:
 access_key_id: AKIAIJUGMKYECWUFG2VQ
 secret_access_key: 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
 bucket: mtm_test_data
